// Example flow — echoes input through the mock provider
// Generated by `runcor init`

export default async function hello(ctx) {
  const input = ctx.input;
  const name = input?.name ?? 'World';

  const response = await ctx.model.complete({
    prompt: `Say hello to ${name}`,
  });

  return { greeting: response.text };
}
