// Agent types for the Agent Execution Pattern

import type { ToolCallResult } from '../types.js';

// ── Stop Reason ──

/** Why the agent loop terminated */
export type StopReason =
  | 'completed'
  | 'max_iterations'
  | 'budget_exhausted'
  | 'timeout'
  | 'context_overflow';

// ── Conversation Types ──

/** A message in the agent's conversation history (provider-agnostic) */
export interface ConversationMessage {
  /** Message role */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** Message content */
  content: string;
  /** Tool calls requested by the model (assistant messages only) */
  toolCalls?: ToolCallRequest[];
  /** ID linking this result to the assistant's tool call request (tool messages only) */
  toolCallId?: string;
  /** Qualified name of the tool that produced this result (tool messages only) */
  toolName?: string;
}

/** A tool call requested by the model in an assistant message */
export interface ToolCallRequest {
  /** Unique ID for this tool call (generated by the model provider) */
  id: string;
  /** Qualified tool name the model wants to invoke */
  name: string;
  /** Arguments the model provided */
  arguments: Record<string, unknown>;
}

/** Tool definition sent to the model so it knows what tools are available */
export interface ToolDefinition {
  /** Qualified tool name */
  name: string;
  /** What the tool does */
  description: string;
  /** JSON Schema for the tool's arguments */
  inputSchema: Record<string, unknown>;
}

// ── Agent Configuration ──

/** Configuration for an agent flow, provided to createAgentHandler() */
export interface AgentConfig {
  /** System prompt defining the agent's role, goal, and behavior */
  systemPrompt: string;
  /** Qualified tool names (e.g., "gmail.sendEmail") available to the agent */
  tools?: string[];
  /** Maximum iterations before hard stop. Default: 25 */
  maxIterations?: number;
  /** Max cost in dollars across all iterations */
  iterationBudget?: number;
  /** Max wall-clock time in ms for the entire agent loop */
  timeoutMs?: number;
  /** JSON Schema describing expected final answer shape (advisory) */
  outputSchema?: Record<string, unknown>;
  /** Max conversation messages to retain; oldest truncated (system prompt always kept) */
  maxHistoryMessages?: number;
}

// ── Agent Result Types ──

/** Record of a single tool call within an iteration */
export interface ToolCallRecord {
  /** Qualified tool name (e.g., "gmail.searchEmails") */
  toolName: string;
  /** Arguments passed to the tool */
  arguments: Record<string, unknown>;
  /** The tool's response */
  result: ToolCallResult;
  /** Time spent on this tool call in ms */
  durationMs: number;
  /** Whether the tool call returned an error */
  isError: boolean;
}

/** Per-iteration record stored in AgentResult.iterations */
export interface AgentIteration {
  /** 1-based iteration number */
  iteration: number;
  /** Tools invoked this iteration (may be empty on final iteration) */
  toolCalls: ToolCallRecord[];
  /** Model used for this iteration's completion */
  model: string;
  /** Token usage for this iteration */
  tokens: { input: number; output: number };
  /** Cost for this iteration */
  cost: number;
  /** Wall-clock time for this iteration (model call + tool calls) in ms */
  durationMs: number;
}

/** The output returned by an agent execution */
export interface AgentResult {
  /** The final model response (parsed JSON if output schema matched, raw text otherwise) */
  answer: unknown;
  /** Why the agent stopped */
  stopReason: StopReason;
  /** Per-iteration metadata array */
  iterations: AgentIteration[];
  /** Cumulative cost across all iterations */
  totalCost: number;
  /** Cumulative token usage */
  totalTokens: { input: number; output: number };
  /** Final conversation history message count */
  conversationLength: number;
}

// ── Validation ──

/** Default max iterations when not configured */
export const DEFAULT_MAX_ITERATIONS = 25;

/** Qualified tool name pattern: "adapterName.toolName" with exactly one dot */
const QUALIFIED_NAME_PATTERN = /^[^.]+\.[^.]+$/;

/** Validate an AgentConfig, throwing EngineError on invalid input */
export function validateAgentConfig(config: AgentConfig): void {
  if (!config.systemPrompt || config.systemPrompt.trim().length === 0) {
    throw new Error('AgentConfig: systemPrompt must be a non-empty string');
  }

  if (config.maxIterations !== undefined && config.maxIterations < 1) {
    throw new Error('AgentConfig: maxIterations must be >= 1');
  }

  if (config.iterationBudget !== undefined && config.iterationBudget <= 0) {
    throw new Error('AgentConfig: iterationBudget must be > 0');
  }

  if (config.timeoutMs !== undefined && config.timeoutMs <= 0) {
    throw new Error('AgentConfig: timeoutMs must be > 0');
  }

  if (config.maxHistoryMessages !== undefined && config.maxHistoryMessages < 2) {
    throw new Error('AgentConfig: maxHistoryMessages must be >= 2');
  }

  if (config.tools) {
    for (const tool of config.tools) {
      if (!QUALIFIED_NAME_PATTERN.test(tool)) {
        throw new Error(
          `AgentConfig: tool name "${tool}" must be a qualified name with exactly one dot (e.g., "adapter.toolName")`,
        );
      }
    }
  }
}
