#!/bin/bash
BASE="http://localhost:3000"
R() { curl -s -X POST "$BASE/api/register" -H 'Content-Type: application/json' -d "$1" > /dev/null; }

R '{"name":"lead-qualifier","type":"prompt","description":"Qualify inbound sales leads","systemPrompt":"You are a B2B sales analyst. Return qualification score 1-10, key signals, next action.","promptTemplate":"Qualify:\nCompany: {{company}}\nTitle: {{title}}\nSource: {{source}}\nNotes: {{notes}}"}'
R '{"name":"contract-summarizer","type":"prompt","description":"Summarize legal contracts","systemPrompt":"You are a legal analyst. Extract key terms, obligations, deadlines, risks.","promptTemplate":"Summarize:\n{{contract}}"}'
R '{"name":"support-triage","type":"agent","description":"Triage customer support tickets","systemPrompt":"You are a support triage agent. Determine severity P1-P4, categorize, suggest response, route.","maxIterations":3}'
R '{"name":"meeting-notes","type":"prompt","description":"Extract action items from meetings","systemPrompt":"You are a meeting analyst. Extract decisions, action items with owners, deadlines.","promptTemplate":"Extract action items:\n{{transcript}}"}'
R '{"name":"invoice-processor","type":"prompt","description":"Parse and validate invoices","systemPrompt":"You are an AP analyst. Extract vendor, amount, line items, due date. Flag discrepancies.","promptTemplate":"Process invoice:\n{{invoice}}"}'
R '{"name":"competitive-intel","type":"agent","description":"Analyze competitive landscape","systemPrompt":"You are a competitive intelligence analyst. Identify threats, opportunities, recommend responses.","maxIterations":3}'
R '{"name":"expense-validator","type":"prompt","description":"Validate employee expense reports","systemPrompt":"You are an AP clerk. Validate against policy. Flag violations. Calculate totals.","promptTemplate":"Validate:\nEmployee: {{employee}}\nDepartment: {{department}}\nPeriod: {{period}}\nExpenses:\n{{expenses}}"}'
R '{"name":"helpdesk-router","type":"agent","description":"Classify and route IT helpdesk tickets","systemPrompt":"You are an IT helpdesk triage agent. Classify, determine severity, identify team, draft response.","maxIterations":3}'
R '{"name":"vendor-onboarding","type":"prompt","description":"Process new vendor applications","systemPrompt":"You are a procurement analyst. Review apps, verify docs, assess risk, generate checklist.","promptTemplate":"Vendor:\n{{vendor}}\nCategory: {{category}}\nDocs: {{documents}}\nValue: {{value}}\nNotes: {{notes}}"}'
R '{"name":"compliance-checker","type":"agent","description":"Audit documents for regulatory compliance","systemPrompt":"You are a compliance officer. Audit against SOX, GDPR. Rate Red/Amber/Green.","maxIterations":4}'
R '{"name":"sla-monitor","type":"prompt","description":"Analyze SLA performance and flag breaches","systemPrompt":"You are an operations analyst. Identify breaches, near-misses, recommend corrections.","promptTemplate":"SLA Analysis:\nService: {{service}}\nPeriod: {{period}}\nTargets: {{targets}}\nMetrics: {{metrics}}"}'
R '{"name":"team-performance-digest","type":"prompt","description":"Weekly team performance summaries","systemPrompt":"You are a management consultant. Synthesize metrics into actionable digest with RAG.","promptTemplate":"Digest:\nTeam: {{team}}\nManager: {{manager}}\nPeriod: {{period}}\nMetrics: {{metrics}}\nEvents: {{events}}"}'
R '{"name":"budget-variance-analyzer","type":"prompt","description":"Budget vs actuals analysis","systemPrompt":"You are a financial planning analyst. Variances, drivers, year-end projection.","promptTemplate":"Variance:\nDept: {{department}}\nQtr: {{quarter}}\nBudget: {{budget}}\nActuals: {{actuals}}\nPrior: {{priorYear}}"}'
R '{"name":"hiring-pipeline-review","type":"agent","description":"Evaluate candidates and recommend decisions","systemPrompt":"You are a senior talent acquisition partner. Assess candidates, rank, recommend panel.","maxIterations":4}'
R '{"name":"project-status-rollup","type":"prompt","description":"Portfolio status aggregation","systemPrompt":"You are a PMO analyst. Aggregate into portfolio view with RAG, milestones, escalations.","promptTemplate":"Rollup:\nPortfolio: {{portfolio}}\nPeriod: {{period}}\nProjects:\n{{projects}}"}'
R '{"name":"risk-register-update","type":"agent","description":"Enterprise risk register assessment","systemPrompt":"You are an enterprise risk manager. Reassess scores, emerging risks, mitigations, 5x5 matrix.","maxIterations":4}'
R '{"name":"ceo-daily-briefing","type":"agent","description":"CEO daily corporate overview email","systemPrompt":"You are Chief of Staff to a Fortune 500 CEO. Concise daily briefing. Crisp executive style. Flag RED items.","maxIterations":5}'
R '{"name":"board-deck-builder","type":"agent","description":"Board meeting presentation narratives","systemPrompt":"You are an IR director. Draft executive narratives for board deck sections. Flag likely questions.","maxIterations":5}'
R '{"name":"ma-target-screener","type":"agent","description":"M&A acquisition target evaluation","systemPrompt":"You are a corp dev VP. Evaluate fit, financials, tech, integration risk. Valuation. Proceed or pass.","maxIterations":5}'
R '{"name":"market-position-analysis","type":"prompt","description":"Strategic market positioning","systemPrompt":"You are a strategy consultant. Five Forces analysis, strategic options, invest/maintain/divest.","promptTemplate":"Position:\nCompany: {{company}}\nIndustry: {{industry}}\nRevenue: {{revenue}}\nShare: {{marketShare}}\nCompetitors: {{competitors}}\nDevelopments: {{developments}}"}'
R '{"name":"quarterly-earnings-narrative","type":"prompt","description":"Quarterly earnings commentary","systemPrompt":"You are the CFO. Draft 2-minute earnings narrative. Revenue, margins, segments, guidance.","promptTemplate":"Q{{quarter}} FY{{year}}:\nRevenue: {{revenue}}\nGuidance: {{guidance}}\nMargins: {{margins}}\nSegments: {{segments}}\nCash: {{cash}}\nHeadcount: {{headcount}}\nWins: {{wins}}\nChallenges: {{challenges}}"}'

echo "21 flows registered"
