// runcor init — scaffold a new project

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { basename, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CommandDef } from '../index.js';
import { formatError, formatSuccess } from '../output.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function getTemplatePath(name: string): string {
  // In dist: dist/cli/commands/init.js → dist/cli/templates/
  return resolve(__dirname, '..', 'templates', name);
}

export const initCommand: CommandDef = {
  name: 'init',
  description: 'Initialize a new Runcor project',
  usage: 'runcor init [--name <project-name>] [--force]',
  options: {
    name: { type: 'string', short: 'n', description: 'Project name in generated config' },
    force: { type: 'boolean', short: 'f', default: false, description: 'Overwrite existing files' },
  },
  handler: async ({ values, positionals }) => {
    const force = values['force'] === true;
    const projectName = (values['name'] as string) ?? positionals[0] ?? basename(process.cwd());

    // Check for existing files
    const configPath = resolve(process.cwd(), 'runcor.yaml');
    if (existsSync(configPath) && !force) {
      console.error(formatError('EXISTS', 'runcor.yaml already exists. Use --force to overwrite.'));
      process.exit(1);
    }

    // Read templates
    let configTemplate: string;
    let flowTemplate: string;
    try {
      configTemplate = readFileSync(getTemplatePath('runcor.yaml'), 'utf-8');
      flowTemplate = readFileSync(getTemplatePath('example-flow.mjs'), 'utf-8');
    } catch {
      // Fallback: inline templates if file read fails (e.g., bundled differently)
      configTemplate = `# Runcor Configuration — {{PROJECT_NAME}}\n# Generated by \`runcor init\`\n\nproviders:\n  - type: mock\n\nhttpServer:\n  enabled: true\n  port: 3000\n`;
      flowTemplate = `// Example flow\nexport default async function hello(ctx) {\n  const input = ctx.input;\n  const name = input?.name ?? 'World';\n  const response = await ctx.model.complete({\n    prompt: \`Say hello to \${name}\`,\n  });\n  return { greeting: response.text };\n}\n`;
    }

    // Substitute template variables
    const configContent = configTemplate.replace(/\{\{PROJECT_NAME\}\}/g, projectName);

    // Write files
    writeFileSync(configPath, configContent, 'utf-8');
    console.log('Created runcor.yaml');

    const flowDir = resolve(process.cwd(), 'flows');
    if (!existsSync(flowDir)) {
      mkdirSync(flowDir, { recursive: true });
    }
    const flowPath = resolve(flowDir, 'hello.mjs');
    writeFileSync(flowPath, flowTemplate, 'utf-8');
    console.log('Created flows/hello.mjs');

    console.log('');
    console.log(formatSuccess('Run `runcor dev` to start the engine.'));
  },
};
